name: simha_link
description: "A mobile app for crowd management and control built with Flutter and Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1
  cloud_functions: 5.6.2
  
  # Map and Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.0
  geolocator: ^12.0.0
  flutter_map_marker_cluster: ^1.4.0
  http: ^1.1.0
  flutter_map_tile_caching: ^9.0.2
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.3

  
  # UI Components
  flutter_map_animations: ^0.8.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
        - asset: assets/fonts/InstrumentSerif-Italic.ttf
