name: simha_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1
  
  # Map and Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.0
  geolocator: ^12.0.0
  flutter_map_marker_cluster: ^1.4.0
  http: ^1.1.0

  
  # UI Components
  flutter_map_animations: ^0.8.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
        - asset: assets/fonts/InstrumentSerif-Italic.ttf
